spring:
  application:
    title: Local-Sandbox
  banner:
    location: local.txt

  data:
    mongodb:
      host: localhost
      port: 27017
      database: PetziDB
      repositories:
        type: auto

  session:
    store-type: mongodb
    timeout.seconds: 60